ALTER TABLE restaurants
  ADD COLUMN IF NOT EXISTS delivery_radius_km DECIMAL(5,2) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS latitude           DECIMAL(10,7) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS longitude          DECIMAL(10,7) DEFAULT NULL;
